added basic error handling
Deletes temp files and unsets variables if an error occurs. Variables also unset when properly exited.

diff --git a/quicced b/quicced
--- a/quicced
+++ b/quicced
@@ -6,15 +6,17 @@
 # Run the following to enable logging
 # quicced.sh 2>&1 | tee -a quicced.log
 
-# Variables
+# Various files
 rc=/etc/rc.conf
 bootcfg=/boot/loader.conf
 xinitrc=/home/$acc/.xinitrc
 fstab=/etc/fstab
 sysctl=/etc/sysctl.conf
 jailrc=/etc/jail.conf
-template=output
-custom=quicced-template
+template=/tmp/output
+custom=/tmp/quicced-template
+
+trap error 1 2 3 6
 
 # Main Menu
 main() {
@@ -104,11 +106,19 @@ main() {
 			# Remove duplicate lines from template
 			awk '!visited[$0]++' $template > $custom
 			rm -rf $template
+			unset $rc
+			unset $bootcfg
+			unset $xinitrc
+			unset $fstab
+			unset $sysctl
+			unset $jailrc
+			unset $template
+			unset $custom
 			clear
 			echo "###################################################################"
 			echo "#                                                                 #"
 			echo "# Some changes may require you to reboot for them to take effect. #"
-			echo "# Make sure you look over the temaple before running it.          #"
+			echo "# Your template is located at /tmp/quicced-template               #"
 			echo "#                                                                 #"
 			echo "###################################################################"
 			exit 0
@@ -685,7 +695,7 @@ server() {
 			server
 			;;
 		
-		# Sevure MariaDB	
+		# Secure MariaDB	
 		2)
 			mysql_secure_installation
 			echo "mysql_secure_installation" >> $template
@@ -806,11 +816,27 @@ compat() {
 	fi
 }
 
+# Cleanup files and variables
+error() {
+	echo "Error: Something went wrong, quitting..."
+	rm -rf $template
+	unset $rc
+	unset $bootcfg
+	unset $xinitrc
+	unset $fstab
+	unset $sysctl
+	unset $jailrc
+	unset $template
+	unset $custom
+	echo "Done!"
+	exit 1
+}
+
 # Check if root
 if [ $(id -u) != 0 ];
 then
 	echo "Must be run as root!"
-	exit 1
+	exit 2
 fi
 
 
@@ -852,5 +878,5 @@ then
 	main
 else
 	echo "Only i386 & amd64 are supported!"
-	exit 1
+	exit 2
 fi
